name: Laravel

on:
  push:
 

jobs:
  build-master:
    runs-on: simevihost
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Run Script
      run: |
        cd ${{vars.GIT_WORKDIR_MASTER}}
        git pull
        composer install
        npm install
        npm run prod
        chmod +x artisan
        ./artisan up
        ./artisan optimize:clear
        ./artisan optimize

