name: Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  build-master:
    runs-on: self-host
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Run Script
      run: |
        cd ${{vars.GIT_WORKDIR_MASTER}}
        git pull
        composer install
        npm install
        npm run prod
        chmod +x artisan
        ./artisan up
        ./artisan optimize:clear
        ./artisan optimize

